server:
  port: 7777
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /@project.artifactId@

# elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.100.254
      cluster-port: 29200
      username: elastic
      password: Od_48923%dlocl802qWc 
      